wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.13
    is_jupyter_run: false
    python_version: 3.5.2
checkpoint_path:
  desc: null
  value: null
dataset:
  desc: null
  value: RGBT-234
experiment_name:
  desc: null
  value: SiamRPN
modality:
  desc: null
  value: 1
